channel_names: 
    - "AIN0"
    - "AIN1"
    - "AIN2"
    - "AIN3"
channel_addresses:
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 14
device_type: "ANY"
conn_type: "ANY"
identifier: "ANY"
use_channel_names: false
streaming: false
verbose: false