device_type: "ANY"
conn_type: "ANY"
identifier: "ANY"

pubrate: 100
scanrate: 100
scansperread: 1

streampubtopic: "/labjack/channelstream"

use_channel_names: false
streaming: true
verbose: true

config_registers:
    - address: "DIO4_EF_ENABLE"
      value: 0
    - address: "DIO4_EF_INDEX"
      value: 11
    - address: "DIO4_EF_ENABLE"
      value: 1

channel_names: 
    - "DIO4_EF_READ_A"
channel_addresses:
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 14